import React, { createContext, useContext, useState } from 'react';

type Language = 'english' | 'hindi' | 'bengali' | 'tamil' | 'telugu' | 'marathi' | 'gujarati' | 'odia';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  english: {
    'nav.dashboard': 'Dashboard',
    'nav.habits': 'Habits',
    'nav.insights': 'Insights',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    'nav.login': 'Log In',
    'nav.getStarted': 'Get Started',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and settings',
    'settings.tabs.profile': 'Profile',
    'settings.tabs.password': 'Password',
    'settings.tabs.preferences': 'Preferences',
    'settings.tabs.notifications': 'Notifications',
    'settings.profile.title': 'Profile Information',
    'settings.profile.description': 'Update your personal information',
    'settings.profile.name': 'Full Name',
    'settings.profile.email': 'Email',
    'settings.profile.save': 'Save Changes',
    'settings.password.title': 'Change Password',
    'settings.password.description': 'Update your password to keep your account secure',
    'settings.password.current': 'Current Password',
    'settings.password.new': 'New Password',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.requirement': 'Password must be at least 8 characters long',
    'settings.password.change': 'Change Password',
    'settings.preferences.title': 'Preferences',
    'settings.preferences.description': 'Customize your app experience',
    'settings.preferences.theme': 'Theme',
    'settings.preferences.language': 'Language',
    'settings.preferences.timezone': 'Time Zone',
    'settings.preferences.save': 'Save Preferences',
    'settings.notifications.title': 'Notification Settings',
    'settings.notifications.description': 'Manage how and when you want to be notified',
    'settings.notifications.email': 'Email Reminders',
    'settings.notifications.emailDesc': 'Receive reminder emails for your habits',
    'settings.notifications.inApp': 'In-App Alerts',
    'settings.notifications.inAppDesc': 'Show notifications within the app',
    'settings.notifications.save': 'Save Notification Settings',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System Default',
    'toast.profileUpdated': 'Profile Updated',
    'toast.profileUpdatedDesc': 'Your profile information has been updated successfully.',
    'toast.passwordChanged': 'Password Changed',
    'toast.passwordChangedDesc': 'Your password has been changed successfully.',
    'toast.preferencesSaved': 'Preferences Saved',
    'toast.preferencesSavedDesc': 'Your preferences have been updated successfully.',
    'toast.notificationsSaved': 'Notification Settings Saved',
    'toast.notificationsSavedDesc': 'Your notification preferences have been updated.',
  },
  hindi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.habits': 'आदतें',
    'nav.insights': 'अंतर्दृष्टि',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉग आउट',
    'nav.login': 'लॉग इन',
    'nav.getStarted': 'शुरू करें',
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपने खाते की प्राथमिकताएँ और सेटिंग्स प्रबंधित करें',
    'settings.tabs.profile': 'प्रोफ़ाइल',
    'settings.tabs.password': 'पासवर्ड',
    'settings.tabs.preferences': 'प्राथमिकताएँ',
    'settings.tabs.notifications': 'सूचनाएँ',
    'settings.profile.title': 'प्रोफ़ाइल जानकारी',
    'settings.profile.description': 'अपनी व्यक्तिगत जानकारी अपडेट करें',
    'settings.profile.name': 'पूरा नाम',
    'settings.profile.email': 'ईमेल',
    'settings.profile.save': 'परिवर्तन सहेजें',
    'settings.password.title': 'पासवर्ड बदलें',
    'settings.password.description': 'अपने खाते की सुरक्षा के लिए अपना पासवर्ड अपडेट करें',
    'settings.password.current': 'वर्तमान पासवर्ड',
    'settings.password.new': 'नया पासवर्ड',
    'settings.password.confirm': 'नए पासवर्ड की पुष्टि करें',
    'settings.password.requirement': 'पासवर्ड कम से कम 8 वर्ण लंबा होना चाहिए',
    'settings.password.change': 'पासवर्ड बदलें',
    'settings.preferences.title': 'प्राथमिकताएँ',
    'settings.preferences.description': 'अपने ऐप अनुभव को अनुकूलित करें',
    'settings.preferences.theme': 'थीम',
    'settings.preferences.language': 'भाषा',
    'settings.preferences.timezone': 'समय क्षेत्र',
    'settings.preferences.save': 'प्राथमिकताएँ सहेजें',
    'settings.notifications.title': 'सूचना सेटिंग्स',
    'settings.notifications.description': 'प्रबंधित करें कि आप कैसे और कब सूचित किया जाना चाहते हैं',
    'settings.notifications.email': 'ईमेल अनुस्मारक',
    'settings.notifications.emailDesc': 'अपनी आदतों के लिए अनुस्मारक ईमेल प्राप्त करें',
    'settings.notifications.inApp': 'ऐप में सूचनाएँ',
    'settings.notifications.inAppDesc': 'ऐप के अंदर सूचनाएँ दिखाएँ',
    'settings.notifications.save': 'सूचना सेटिंग्स सहेजें',
    'theme.light': 'उजला',
    'theme.dark': 'गहरा',
    'theme.system': 'सिस्टम डिफॉल्ट',
    'toast.profileUpdated': 'प्रोफ़ाइल अपडेट किया गया',
    'toast.profileUpdatedDesc': 'आपकी प्रोफ़ाइल जानकारी सफलतापूर्वक अपडेट की गई है।',
    'toast.passwordChanged': 'पासवर्ड बदला गया',
    'toast.passwordChangedDesc': 'आपका पासवर्ड सफलतापूर्वक बदल दिया गया है।',
    'toast.preferencesSaved': 'प्राथमिकताएँ सहेजी गईं',
    'toast.preferencesSavedDesc': 'आपकी प्राथमिकताएँ सफलतापूर्वक अपडेट की गई हैं।',
    'toast.notificationsSaved': 'सूचना सेटिंग्स सहेजी गईं',
    'toast.notificationsSavedDesc': 'आपकी सूचना प्राथमिकताएँ अपडेट की गई हैं।',
  },
  bengali: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.habits': 'অভ্যাস',
    'nav.insights': 'অন্তর্দৃষ্টি',
    'nav.settings': 'সেটিংস',
    'nav.logout': 'লগ আউট',
    'nav.login': 'লগ ইন',
    'nav.getStarted': 'শুরু করুন',
    'settings.title': 'সেটিংস',
    'settings.subtitle': 'আপনার অ্যাকাউন্ট পছন্দ এবং সেটিংস পরিচালনা করুন',
    'settings.tabs.profile': 'প্রোফাইল',
    'settings.tabs.password': 'পাসওয়ার্ড',
    'settings.tabs.preferences': 'পছন্দসমূহ',
    'settings.tabs.notifications': 'বিজ্ঞপ্তি',
    'settings.profile.title': 'প্রোফাইল তথ্য',
    'settings.profile.description': 'আপনার ব্যক্তিগত তথ্য আপডেট করুন',
    'settings.profile.name': 'সম্পূর্ণ নাম',
    'settings.profile.email': 'ইমেইল',
    'settings.profile.save': 'পরিবর্তন সংরক্ষণ করুন',
    'settings.password.title': 'পাসওয়ার্ড পরিবর্তন করুন',
    'settings.password.description': 'আপনার অ্যাকাউন্ট সুরক্ষিত রাখতে আপনার পাসওয়ার্ড আপডেট করুন',
    'settings.password.current': 'বর্তমান পাসওয়ার্ড',
    'settings.password.new': 'নতুন পাসওয়ার্ড',
    'settings.password.confirm': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'settings.password.requirement': 'পাসওয়ার্ড কমপক্ষে 8 অক্ষর দীর্ঘ হতে হবে',
    'settings.password.change': 'পাসওয়ার্ড পরিবর্তন করুন',
    'settings.preferences.title': 'পছন্দসমূহ',
    'settings.preferences.description': 'আপনার অ্যাপ অভিজ্ঞতা কাস্টমাইজ করুন',
    'settings.preferences.theme': 'থিম',
    'settings.preferences.language': 'ভাষা',
    'settings.preferences.timezone': 'সময় অঞ্চল',
    'settings.preferences.save': 'পছন্দসমূহ সংরক্ষণ করুন',
    'settings.notifications.title': 'বিজ্ঞপ্তি সেটিংস',
    'settings.notifications.description': 'আপনি কীভাবে এবং কখন বিজ্ঞপ্তি পেতে চান তা পরিচালনা করুন',
    'settings.notifications.email': 'ইমেইল রিমাইন্ডার',
    'settings.notifications.emailDesc': 'আপনার অভ্যাসের জন্য রিমাইন্ডার ইমেইল পান',
    'settings.notifications.inApp': 'অ্যাপে সতর্কতা',
    'settings.notifications.inAppDesc': 'অ্যাপের মধ্যে বিজ্ঞপ্তি দেখান',
    'settings.notifications.save': 'বিজ্ঞপ্তি সেটিংস সংরক্ষণ করুন',
    'theme.light': 'হালকা',
    'theme.dark': 'গাঢ়',
    'theme.system': 'সিস্টেম ডিফল্ট',
    'toast.profileUpdated': 'প্রোফাইল আপডেট হয়েছে',
    'toast.profileUpdatedDesc': 'আপনার প্রোফাইল তথ্য সফলভাবে আপডেট করা হয়েছে।',
    'toast.passwordChanged': 'পাসওয়ার্ড পরিবর্তন করা হয়েছে',
    'toast.passwordChangedDesc': 'আপনার পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে।',
    'toast.preferencesSaved': 'পছন্দসমূহ সংরক্ষিত হয়েছে',
    'toast.preferencesSavedDesc': 'আপনার পছন্দসমূহ সফলভাবে আপডেট করা হয়েছে।',
    'toast.notificationsSaved': 'বিজ্ঞপ্তি সেটিংস সংরক্ষিত হয়েছে',
    'toast.notificationsSavedDesc': 'আপনার বিজ্ঞপ্তি পছন্দসমূহ আপডেট করা হয়েছে।',
  },
  tamil: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.habits': 'பழக்கங்கள்',
    'nav.insights': 'நுண்ணறிவுகள்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    'nav.login': 'உள்நுழைக',
    'nav.getStarted': 'தொடங்கவும்',
    'settings.title': 'அமைப்புகள்',
    'settings.subtitle': 'உங்கள் கணக்கு விருப்பங்கள் மற்றும் அமைப்புகளை நிர்வகிக்கவும்',
    'settings.tabs.profile': 'சுயவிவரம்',
    'settings.tabs.password': 'கடவுச்சொல்',
    'settings.tabs.preferences': 'விருப்பங்கள்',
    'settings.tabs.notifications': 'அறிவிப்புகள்',
    'settings.profile.title': 'சுயவிவர தகவல்',
    'settings.profile.description': 'உங்கள் தனிப்பட்ட தகவலைப் புதுப்பிக்கவும்',
    'settings.profile.name': 'முழு பெயர்',
    'settings.profile.email': 'மின்னஞ்சல்',
    'settings.profile.save': 'மாற்றங்களை சேமி',
    'settings.password.title': 'கடவுச்சொல்லை மாற்று',
    'settings.password.description': 'உங்கள் கணக்கைப் பாதுகாப்பாக வைத்திருக்க உங்கள் கடவுச்சொல்லைப் புதுப்பிக்கவும்',
    'settings.password.current': 'தற்போதைய கடவுச்சொல்',
    'settings.password.new': 'புதிய கடவுச்சொல்',
    'settings.password.confirm': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'settings.password.requirement': 'கடவுச்சொல் குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்',
    'settings.password.change': 'கடவுச்சொல்லை மாற்றவும்',
    'settings.preferences.title': 'விருப்பங்கள்',
    'settings.preferences.description': 'உங்கள் பயன்பாட்டு அனுபவத்தை தனிப்பயனாக்கவும்',
    'settings.preferences.theme': 'தீம்',
    'settings.preferences.language': 'மொழி',
    'settings.preferences.timezone': 'நேர மண்டலம்',
    'settings.preferences.save': 'விருப்பங்களை சேமி',
    'settings.notifications.title': 'அறிவிப்பு அமைப்புகள்',
    'settings.notifications.description': 'எப்படி மற்றும் எப்போது நீங்கள் அறிவிக்கப்பட விரும்புகிறீர்கள் என்பதை நிர்வகிக்கவும்',
    'settings.notifications.email': 'மின்னஞ்சல் நினைவூட்டல்கள்',
    'settings.notifications.emailDesc': 'உங்கள் பழக்கங்களுக்கான நினைவூட்டல் மின்னஞ்சல்களைப் பெறுங்கள்',
    'settings.notifications.inApp': 'பயன்பாட்டில் எச்சரிக்கைகள்',
    'settings.notifications.inAppDesc': 'பயன்பாட்டிற்குள் அறிவிப்புகளைக் காட்டு',
    'settings.notifications.save': 'அறிவிப்பு அமைப்புகளை சேமி',
    'theme.light': 'வெளிச்சம்',
    'theme.dark': 'இருள்',
    'theme.system': 'சிஸ்டம் இயல்புநிலை',
    'toast.profileUpdated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது',
    'toast.profileUpdatedDesc': 'உங்கள் சுயவிவர தகவல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
    'toast.passwordChanged': 'கடவுச்சொல் மாற்றப்பட்டது',
    'toast.passwordChangedDesc': 'உங்கள் கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது.',
    'toast.preferencesSaved': 'விருப்பங்கள் சேமிக்கப்பட்டன',
    'toast.preferencesSavedDesc': 'உங்கள் விருப்பங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன.',
    'toast.notificationsSaved': 'அறிவிப்பு அமைப்புகள் சேமிக்கப்பட்டன',
    'toast.notificationsSavedDesc': 'உங்கள் அறிவிப்பு விருப்பங்கள் புதுப்பிக்கப்பட்டன.',
  },
  telugu: {
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.habits': 'అలవాట్లు',
    'nav.insights': 'అంతర్దృష్టులు',
    'nav.settings': 'సెట్టింగులు',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.login': 'లాగిన్',
    'nav.getStarted': 'ప్రారంభించండి',
    'settings.title': 'సెట్టింగులు',
    'settings.subtitle': 'మీ ఖాతా ప్రాధాన్యతలు మరియు సెట్టింగులను నిర్వహించండి',
    'settings.tabs.profile': 'ప్రొఫైల్',
    'settings.tabs.password': 'పాస్‌వర్డ్',
    'settings.tabs.preferences': 'ప్రాధాన్యతలు',
    'settings.tabs.notifications': 'నోటిఫికేషన్లు',
    'settings.profile.title': 'ప్రొఫైల్ సమాచారం',
    'settings.profile.description': 'మీ వ్యక్తిగత సమాచారాన్ని నవీకరించండి',
    'settings.profile.name': 'పూర్తి పేరు',
    'settings.profile.email': 'ఇమెయిల్',
    'settings.profile.save': 'మార్పులు సేవ్ చేయండి',
    'settings.password.title': 'పాస్‌వర్డ్ మార్చండి',
    'settings.password.description': 'మీ ఖాతాను సురక్షితంగా ఉంచడానికి మీ పాస్‌వర్డ్‌ని నవీకరించండి',
    'settings.password.current': 'ప్రస్తుత పాస్‌వర్డ్',
    'settings.password.new': 'కొత్త పాస్‌వర్డ్',
    'settings.password.confirm': 'కొత్త పాస్‌వర్డ్‌ని నిర్ధారించండి',
    'settings.password.requirement': 'పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి',
    'settings.password.change': 'పాస్‌వర్డ్ మార్చండి',
    'settings.preferences.title': 'ప్రాధాన్యతలు',
    'settings.preferences.description': 'మీ అనుభవాన్ని అనుకూలీకరించండి',
    'settings.preferences.theme': 'థీమ్',
    'settings.preferences.language': 'భాష',
    'settings.preferences.timezone': 'టైమ్ జోన్',
    'settings.preferences.save': 'ప్రాధాన్యతలు సేవ్ చేయండి',
    'settings.notifications.title': 'నోటిఫికేషన్ సెట్టింగులు',
    'settings.notifications.description': 'మీకు ఎలా మరియు ఎప్పుడు తెలియజేయాలో నిర్వహించండి',
    'settings.notifications.email': 'ఇమెయిల్ రిమైండర్లు',
    'settings.notifications.emailDesc': 'మీ అలవాట్లకు రిమైండర్ ఇమెయిల్‌లను పొందండి',
    'settings.notifications.inApp': 'యాప్‌లో అలర్ట్‌లు',
    'settings.notifications.inAppDesc': 'యాప్‌లో నోటిఫికేషన్‌లను చూపించు',
    'settings.notifications.save': 'నోటిఫికేషన్ సెట్టింగులను సేవ్ చేయండి',
    'theme.light': 'లైట్',
    'theme.dark': 'డార్క్',
    'theme.system': 'సిస్టమ్ డిఫాల్ట్',
    'toast.profileUpdated': 'ప్రొఫైల్ అప్డేట్ అయ్యింది',
    'toast.profileUpdatedDesc': 'మీ ప్రొఫైల్ సమాచారం విజయవంతంగా అప్డేట్ చేయబడింది.',
    'toast.passwordChanged': 'పాస్‌వర్డ్ మార్చబడింది',
    'toast.passwordChangedDesc': 'మీ పాస్‌వర్డ్ విజయవంతంగా మార్చబడింది.',
    'toast.preferencesSaved': 'ప్రాధాన్యతలు సేవ్ చేయబడ్డాయి',
    'toast.preferencesSavedDesc': 'మీ ప్రాధాన్యతలు విజయవంతంగా అప్డేట్ చేయబడ్డాయి.',
    'toast.notificationsSaved': 'నోటిఫికేషన్ సెట్టింగులు సేవ్ చేయబడ్డాయి',
    'toast.notificationsSavedDesc': 'మీ నోటిఫికేషన్ ప్రాధాన్యతలు అప్డేట్ చేయబడ్డాయి.',
  },
  marathi: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.habits': 'सवयी',
    'nav.insights': 'अंतर्दृष्टी',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉग आउट',
    'nav.login': 'लॉग इन',
    'nav.getStarted': 'सुरू करा',
    'settings.title': 'सेटिंग्ज',
    'settings.subtitle': 'तुमच्या खात्याच्या प्राधान्यक्रम आणि सेटिंग्ज व्यवस्थापित करा',
    'settings.tabs.profile': 'प्रोफाइल',
    'settings.tabs.password': 'पासवर्ड',
    'settings.tabs.preferences': 'प्राधान्यक्रम',
    'settings.tabs.notifications': 'सूचना',
    'settings.profile.title': 'प्रोफाइल माहिती',
    'settings.profile.description': 'तुमची वैयक्तिक माहिती अपडेट करा',
    'settings.profile.name': 'पूर्ण नाव',
    'settings.profile.email': 'ईमेल',
    'settings.profile.save': 'बदल जतन करा',
    'settings.password.title': 'पासवर्ड बदला',
    'settings.password.description': 'तुमचे खाते सुरक्षित ठेवण्यासाठी तुमचा पासवर्ड अपडेट करा',
    'settings.password.current': 'सध्याचा पासवर्ड',
    'settings.password.new': 'नवीन पासवर्ड',
    'settings.password.confirm': 'नवीन पासवर्ड पुष्टी करा',
    'settings.password.requirement': 'पासवर्ड किमान 8 वर्ण लांब असणे आवश्यक आहे',
    'settings.password.change': 'पासवर्ड बदला',
    'settings.preferences.title': 'प्राधान्यक्रम',
    'settings.preferences.description': 'तुमचा अॅप अनुभव सानुकूल करा',
    'settings.preferences.theme': 'थीम',
    'settings.preferences.language': 'भाषा',
    'settings.preferences.timezone': 'टाइम झोन',
    'settings.preferences.save': 'प्राधान्यक्रम जतन करा',
    'settings.notifications.title': 'सूचना सेटिंग्ज',
    'settings.notifications.description': 'तुम्हाला कसे आणि कधी सूचित केले जावे याचे व्यवस्थापन करा',
    'settings.notifications.email': 'ईमेल रिमाइंडर्स',
    'settings.notifications.emailDesc': 'तुमच्या सवयींसाठी रिमाइंडर ईमेल प्राप्त करा',
    'settings.notifications.inApp': 'अॅपमधील अलर्ट्स',
    'settings.notifications.inAppDesc': 'अॅपमध्ये सूचना दाखवा',
    'settings.notifications.save': 'सूचना सेटिंग्ज जतन करा',
    'theme.light': 'लाइट',
    'theme.dark': 'डार्क',
    'theme.system': 'सिस्टम डीफॉल्ट',
    'toast.profileUpdated': 'प्रोफाइल अपडेट केले',
    'toast.profileUpdatedDesc': 'तुमची प्रोफाइल माहिती यशस्वीरित्या अपडेट केली आहे.',
    'toast.passwordChanged': 'पासवर्ड बदलला',
    'toast.passwordChangedDesc': 'तुमचा पासवर्ड यशस्वीरित्या बदलला गेला आहे.',
    'toast.preferencesSaved': 'प्राधान्यक्रम जतन केले',
    'toast.preferencesSavedDesc': 'तुमचे प्राधान्यक्रम यशस्वीरित्या अपडेट केले आहेत.',
    'toast.notificationsSaved': 'सूचना सेटिंग्ज जतन केल्या',
    'toast.notificationsSavedDesc': 'तुमच्या सूचना प्राधान्यक्रम अपडेट केले आहेत.',
  },
  gujarati: {
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.habits': 'આદતો',
    'nav.insights': 'અંતર્દૃષ્ટિ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.logout': 'લોગ આઉટ',
    'nav.login': 'લોગ ઈન',
    'nav.getStarted': 'શરૂ કરો',
    'settings.title': 'સેટિંગ્સ',
    'settings.subtitle': 'તમારા એકાઉન્ટની પસંદગીઓ અને સેટિંગ્સ મેનેજ કરો',
    'settings.tabs.profile': 'પ્રોફાઇલ',
    'settings.tabs.password': 'પાસવર્ડ',
    'settings.tabs.preferences': 'પસંદગીઓ',
    'settings.tabs.notifications': 'નોટિફિકેશન્સ',
    'settings.profile.title': 'પ્રોફાઇલ માહિતી',
    'settings.profile.description': 'તમારી વ્યક્તિગત માહિતી અપડેટ કરો',
    'settings.profile.name': 'પૂરું નામ',
    'settings.profile.email': 'ઈમેલ',
    'settings.profile.save': 'ફેરફારો સાચવો',
    'settings.password.title': 'પાસવર્ડ બદલો',
    'settings.password.description': 'તમારા એકાઉન્ટને સુરક્ષિત રાખવા માટે તમારો પાસવર્ડ અપડેટ કરો',
    'settings.password.current': 'વર્તમાન પાસવર્ડ',
    'settings.password.new': 'નવો પાસવર્ડ',
    'settings.password.confirm': 'નવા પાસવર્ડની પુષ્ટિ કરો',
    'settings.password.requirement': 'પાસવર્ડ ઓછામાં ઓછો 8 અક્ષરો લાંબો હોવો જોઈએ',
    'settings.password.change': 'પાસવર્ડ બદલો',
    'settings.preferences.title': 'પસંદગીઓ',
    'settings.preferences.description': 'તમારા એપ્લિકેશન અનુભવને કસ્ટમાઇઝ કરો',
    'settings.preferences.theme': 'થીમ',
    'settings.preferences.language': 'ભાષા',
    'settings.preferences.timezone': 'ટાઇમ ઝોન',
    'settings.preferences.save': 'પસંદગીઓ સાચવો',
    'settings.notifications.title': 'નોટિફિકેશન સેટિંગ્સ',
    'settings.notifications.description': 'તમને કેવી રીતે અને ક્યારે જાણ કરવામાં આવે તે મેનેજ કરો',
    'settings.notifications.email': 'ઈમેલ રિમાઇન્ડર્સ',
    'settings.notifications.emailDesc': 'તમારી આદતો માટે રિમાઇન્ડર ઈમેલ્સ મેળવો',
    'settings.notifications.inApp': 'એપમાં એલર્ટ્સ',
    'settings.notifications.inAppDesc': 'એપ્લિકેશનમાં નોટિફિકેશન્સ બતાવો',
    'settings.notifications.save': 'નોટિફિકેશન સેટિંગ્સ સાચવો',
    'theme.light': 'લાઇટ',
    'theme.dark': 'ડાર્ક',
    'theme.system': 'સિસ્ટમ ડિફૉલ્ટ',
    'toast.profileUpdated': 'પ્રોફાઇલ અપડેટ થયું',
    'toast.profileUpdatedDesc': 'તમારી પ્રોફાઇલ માહિતી સફળતાપૂર્વક અપડેટ કરવામાં આવી છે.',
    'toast.passwordChanged': 'પાસવર્ડ બદલાઈ ગયો',
    'toast.passwordChangedDesc': 'તમારો પાસવર્ડ સફળતાપૂર્વક બદલાઈ ગયો છે.',
    'toast.preferencesSaved': 'પસંદગીઓ સાચવવામાં આવી',
    'toast.preferencesSavedDesc': 'તમારી પસંદગીઓ સફળતાપૂર્વક અપડેટ કરવામાં આવી છે.',
    'toast.notificationsSaved': 'નોટિફિકેશન સેટિંગ્સ સાચવવામાં આવી',
    'toast.notificationsSavedDesc': 'તમારી નોટિફિકેશન પસંદગીઓ અપડેટ કરવામાં આવી છે.',
  },
  odia: {
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.habits': 'ଅଭ୍ୟାସ',
    'nav.insights': 'ଅନ୍ତର୍ଦୃଷ୍ଟି',
    'nav.settings': 'ସେଟିଂ',
    'nav.logout': 'ଲଗ ଆଉଟ୍',
    'nav.login': 'ଲଗ ଇନ୍',
    'nav.getStarted': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'settings.title': 'ସେଟିଂସ୍',
    'settings.subtitle': 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ପସନ୍ଦ ଏବଂ ସେଟିଂସ୍ ପରିଚାଳନା କରନ୍ତୁ',
    'settings.tabs.profile': 'ପ୍ରୋଫାଇଲ୍',
    'settings.tabs.password': 'ପାସୱାର୍ଡ',
    'settings.tabs.preferences': 'ପସନ୍ଦ',
    'settings.tabs.notifications': 'ବିଜ୍ଞପ୍ତି',
    'settings.profile.title': 'ପ୍ରୋଫାଇଲ ସୂଚନା',
    'settings.profile.description': 'ଆପଣଙ୍କର ବ୍ୟକ୍ତିଗତ ସୂଚନା ଅପଡେଟ୍ କରନ୍ତୁ',
    'settings.profile.name': 'ପୁରା ନାମ',
    'settings.profile.email': 'ଇମେଲ୍',
    'settings.profile.save': 'ପରିବର୍ତ୍ତନ ସଞ୍ଚୟ କରନ୍ତୁ',
    'settings.password.title': 'ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
    'settings.password.description': 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟକୁ ସୁରକ୍ଷିତ ରଖିବା ପାଇଁ ପାସୱାର୍ଡ ଅପଡେଟ୍ କରନ୍ତୁ',
    'settings.password.current': 'ବର୍ତ୍ତମାନର ପାସୱାର୍ଡ',
    'settings.password.new': 'ନୂଆ ପାସୱାର୍ଡ',
    'settings.password.confirm': 'ନୂଆ ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
    'settings.password.requirement': 'ପାସୱାର୍ଡ ଅତି କମରେ 8 ଅକ୍ଷର ଲମ୍ବା ହେବା ଆବଶ୍ୟକ',
    'settings.password.change': 'ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
    'settings.preferences.title': 'ପସନ୍ଦ',
    'settings.preferences.description': 'ଆପଣଙ୍କ ଆପ୍ ଅନୁଭବକୁ କଷ୍ଟୋମାଇଜ୍ କରନ୍ତୁ',
    'settings.preferences.theme': 'ଥିମ୍',
    'settings.preferences.language': 'ଭାଷା',
    'settings.preferences.timezone': 'ସମୟ କ୍ଷେତ୍ର',
    'settings.preferences.save': 'ପସନ୍ଦଗୁଡ଼ିକ ସଞ୍ଚୟ କରନ୍ତୁ',
    'settings.notifications.title': 'ବିଜ୍ଞପ୍ତି ସେଟିଂସ୍',
    'settings.notifications.description': 'କିପରି ଏବଂ କେବେ ଆପଣଙ୍କୁ ସୂଚିତ କରାଯିବ ତାହା ପରିଚାଳନା କରନ୍ତୁ',
    'settings.notifications.email': 'ଇମେଲ୍ ରିମାଇଣ୍ଡର୍',
    'settings.notifications.emailDesc': 'ଆପଣଙ୍କ ଅଭ୍ୟାସ ପାଇଁ ରିମାଇଣ୍ଡର ଇମେଲ୍ ପାଆନ୍ତୁ',
    'settings.notifications.inApp': 'ଆପ୍ ମଧ୍ୟରେ ଆଲର୍ଟ',
    'settings.notifications.inAppDesc': 'ଆପ୍ ମଧ୍ୟରେ ବିଜ୍ଞପ୍ତି ଦେଖାନ୍ତୁ',
    'settings.notifications.save': 'ବିଜ୍ଞପ୍ତି ସେଟିଂସ୍ ସଞ୍ଚୟ କରନ୍ତୁ',
    'theme.light': 'ହାଲୁକା',
    'theme.dark': 'ଗାଢ଼',
    'theme.system': 'ସିଷ୍ଟମ୍ ଡିଫଲ୍ଟ',
    'toast.profileUpdated': 'ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ ହୋଇଛି',
    'toast.profileUpdatedDesc': 'ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ସୂଚନା ସଫଳତାର ସହିତ ଅପଡେଟ୍ ହୋଇଛି।',
    'toast.passwordChanged': 'ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ ହୋଇଛି',
    'toast.passwordChangedDesc': 'ଆପଣଙ୍କର ପାସୱାର୍ଡ ସଫଳତାର ସହ ପରିବର୍ତ୍ତନ ହୋଇଛି।',
    'toast.preferencesSaved': 'ପସନ୍ଦଗୁଡ଼ିକ ସଞ୍ଚୟ ହୋଇଛି',
    'toast.preferencesSavedDesc': 'ଆପଣଙ୍କର ପସନ୍ଦଗୁଡ଼ିକ ସଫଳତାର ସହିତ ଅପଡେଟ୍ ହୋଇଛି।',
    'toast.notificationsSaved': 'ବିଜ୍ଞପ୍ତି ସେଟିଂସ୍ ସଞ୍ଚୟ ହୋଇଛି',
    'toast.notificationsSavedDesc': 'ଆପଣଙ୍କର ବିଜ୍ଞପ୍ତି ପସନ୍ଦଗୁଡ଼ିକ ଅପଡେଟ୍ ହୋଇଛି।',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'english';
  });

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  React.useEffect(() => {
    localStorage.setItem('language', language);
    console.log('Language changed to:', language);
  }, [language]);

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
};
