
import React, { createContext, useContext, useState } from 'react';

type Language = 'english' | 'spanish' | 'french' | 'german' | 'japanese';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  english: {
    'nav.dashboard': 'Dashboard',
    'nav.habits': 'Habits',
    'nav.insights': 'Insights',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    'nav.login': 'Log In',
    'nav.getStarted': 'Get Started',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and settings',
    'settings.tabs.profile': 'Profile',
    'settings.tabs.password': 'Password',
    'settings.tabs.preferences': 'Preferences',
    'settings.tabs.notifications': 'Notifications',
    'settings.profile.title': 'Profile Information',
    'settings.profile.description': 'Update your personal information',
    'settings.profile.name': 'Full Name',
    'settings.profile.email': 'Email',
    'settings.profile.save': 'Save Changes',
    'settings.password.title': 'Change Password',
    'settings.password.description': 'Update your password to keep your account secure',
    'settings.password.current': 'Current Password',
    'settings.password.new': 'New Password',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.requirement': 'Password must be at least 8 characters long',
    'settings.password.change': 'Change Password',
    'settings.preferences.title': 'Preferences',
    'settings.preferences.description': 'Customize your app experience',
    'settings.preferences.theme': 'Theme',
    'settings.preferences.language': 'Language',
    'settings.preferences.timezone': 'Time Zone',
    'settings.preferences.save': 'Save Preferences',
    'settings.notifications.title': 'Notification Settings',
    'settings.notifications.description': 'Manage how and when you want to be notified',
    'settings.notifications.email': 'Email Reminders',
    'settings.notifications.emailDesc': 'Receive reminder emails for your habits',
    'settings.notifications.inApp': 'In-App Alerts',
    'settings.notifications.inAppDesc': 'Show notifications within the app',
    'settings.notifications.save': 'Save Notification Settings',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System Default',
    'toast.profileUpdated': 'Profile Updated',
    'toast.profileUpdatedDesc': 'Your profile information has been updated successfully.',
    'toast.passwordChanged': 'Password Changed',
    'toast.passwordChangedDesc': 'Your password has been changed successfully.',
    'toast.preferencesSaved': 'Preferences Saved',
    'toast.preferencesSavedDesc': 'Your preferences have been updated successfully.',
    'toast.notificationsSaved': 'Notification Settings Saved',
    'toast.notificationsSavedDesc': 'Your notification preferences have been updated.',
  },
  spanish: {
    'nav.dashboard': 'Panel',
    'nav.habits': 'Hábitos',
    'nav.insights': 'Análisis',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestiona las preferencias y configuración de tu cuenta',
    'settings.tabs.profile': 'Perfil',
    'settings.tabs.password': 'Contraseña',
    'settings.tabs.preferences': 'Preferencias',
    'settings.tabs.notifications': 'Notificaciones',
    'settings.profile.title': 'Información del Perfil',
    'settings.profile.description': 'Actualiza tu información personal',
    'settings.profile.name': 'Nombre Completo',
    'settings.profile.email': 'Correo Electrónico',
    'settings.profile.save': 'Guardar Cambios',
    'settings.password.title': 'Cambiar Contraseña',
    'settings.password.description': 'Actualiza tu contraseña para mantener tu cuenta segura',
    'settings.password.current': 'Contraseña Actual',
    'settings.password.new': 'Nueva Contraseña',
    'settings.password.confirm': 'Confirmar Nueva Contraseña',
    'settings.password.requirement': 'La contraseña debe tener al menos 8 caracteres',
    'settings.password.change': 'Cambiar Contraseña',
    'settings.preferences.title': 'Preferencias',
    'settings.preferences.description': 'Personaliza tu experiencia en la aplicación',
    'settings.preferences.theme': 'Tema',
    'settings.preferences.language': 'Idioma',
    'settings.preferences.timezone': 'Zona Horaria',
    'settings.preferences.save': 'Guardar Preferencias',
    'settings.notifications.title': 'Configuración de Notificaciones',
    'settings.notifications.description': 'Gestiona cómo y cuándo quieres ser notificado',
    'settings.notifications.email': 'Recordatorios por Correo',
    'settings.notifications.emailDesc': 'Recibir correos de recordatorio para tus hábitos',
    'settings.notifications.inApp': 'Alertas en la App',
    'settings.notifications.inAppDesc': 'Mostrar notificaciones dentro de la aplicación',
    'settings.notifications.save': 'Guardar Configuración de Notificaciones',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Predeterminado del Sistema',
    'toast.profileUpdated': 'Perfil Actualizado',
    'toast.profileUpdatedDesc': 'Tu información de perfil ha sido actualizada exitosamente.',
    'toast.passwordChanged': 'Contraseña Cambiada',
    'toast.passwordChangedDesc': 'Tu contraseña ha sido cambiada exitosamente.',
    'toast.preferencesSaved': 'Preferencias Guardadas',
    'toast.preferencesSavedDesc': 'Tus preferencias han sido actualizadas exitosamente.',
    'toast.notificationsSaved': 'Configuración de Notificaciones Guardada',
    'toast.notificationsSavedDesc': 'Tus preferencias de notificación han sido actualizadas.',
  },
  french: {
    'nav.dashboard': 'Tableau de Bord',
    'nav.habits': 'Habitudes',
    'nav.insights': 'Analyses',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Se Déconnecter',
    'nav.login': 'Se Connecter',
    'nav.getStarted': 'Commencer',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez vos préférences et paramètres de compte',
    'settings.tabs.profile': 'Profil',
    'settings.tabs.password': 'Mot de Passe',
    'settings.tabs.preferences': 'Préférences',
    'settings.tabs.notifications': 'Notifications',
    'settings.profile.title': 'Informations du Profil',
    'settings.profile.description': 'Mettez à jour vos informations personnelles',
    'settings.profile.name': 'Nom Complet',
    'settings.profile.email': 'Email',
    'settings.profile.save': 'Sauvegarder les Modifications',
    'settings.password.title': 'Changer le Mot de Passe',
    'settings.password.description': 'Mettez à jour votre mot de passe pour sécuriser votre compte',
    'settings.password.current': 'Mot de Passe Actuel',
    'settings.password.new': 'Nouveau Mot de Passe',
    'settings.password.confirm': 'Confirmer le Nouveau Mot de Passe',
    'settings.password.requirement': 'Le mot de passe doit contenir au moins 8 caractères',
    'settings.password.change': 'Changer le Mot de Passe',
    'settings.preferences.title': 'Préférences',
    'settings.preferences.description': 'Personnalisez votre expérience de l\'application',
    'settings.preferences.theme': 'Thème',
    'settings.preferences.language': 'Langue',
    'settings.preferences.timezone': 'Fuseau Horaire',
    'settings.preferences.save': 'Sauvegarder les Préférences',
    'settings.notifications.title': 'Paramètres de Notification',
    'settings.notifications.description': 'Gérez comment et quand vous voulez être notifié',
    'settings.notifications.email': 'Rappels par Email',
    'settings.notifications.emailDesc': 'Recevoir des emails de rappel pour vos habitudes',
    'settings.notifications.inApp': 'Alertes dans l\'App',
    'settings.notifications.inAppDesc': 'Afficher les notifications dans l\'application',
    'settings.notifications.save': 'Sauvegarder les Paramètres de Notification',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.system': 'Défaut du Système',
    'toast.profileUpdated': 'Profil Mis à Jour',
    'toast.profileUpdatedDesc': 'Vos informations de profil ont été mises à jour avec succès.',
    'toast.passwordChanged': 'Mot de Passe Modifié',
    'toast.passwordChangedDesc': 'Votre mot de passe a été modifié avec succès.',
    'toast.preferencesSaved': 'Préférences Sauvegardées',
    'toast.preferencesSavedDesc': 'Vos préférences ont été mises à jour avec succès.',
    'toast.notificationsSaved': 'Paramètres de Notification Sauvegardés',
    'toast.notificationsSavedDesc': 'Vos préférences de notification ont été mises à jour.',
  },
  german: {
    'nav.dashboard': 'Dashboard',
    'nav.habits': 'Gewohnheiten',
    'nav.insights': 'Einblicke',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    'nav.getStarted': 'Loslegen',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre Kontopräferenzen und -einstellungen',
    'settings.tabs.profile': 'Profil',
    'settings.tabs.password': 'Passwort',
    'settings.tabs.preferences': 'Präferenzen',
    'settings.tabs.notifications': 'Benachrichtigungen',
    'settings.profile.title': 'Profilinformationen',
    'settings.profile.description': 'Aktualisieren Sie Ihre persönlichen Informationen',
    'settings.profile.name': 'Vollständiger Name',
    'settings.profile.email': 'E-Mail',
    'settings.profile.save': 'Änderungen Speichern',
    'settings.password.title': 'Passwort Ändern',
    'settings.password.description': 'Aktualisieren Sie Ihr Passwort, um Ihr Konto sicher zu halten',
    'settings.password.current': 'Aktuelles Passwort',
    'settings.password.new': 'Neues Passwort',
    'settings.password.confirm': 'Neues Passwort Bestätigen',
    'settings.password.requirement': 'Das Passwort muss mindestens 8 Zeichen lang sein',
    'settings.password.change': 'Passwort Ändern',
    'settings.preferences.title': 'Präferenzen',
    'settings.preferences.description': 'Passen Sie Ihre App-Erfahrung an',
    'settings.preferences.theme': 'Design',
    'settings.preferences.language': 'Sprache',
    'settings.preferences.timezone': 'Zeitzone',
    'settings.preferences.save': 'Präferenzen Speichern',
    'settings.notifications.title': 'Benachrichtigungseinstellungen',
    'settings.notifications.description': 'Verwalten Sie, wie und wann Sie benachrichtigt werden möchten',
    'settings.notifications.email': 'E-Mail-Erinnerungen',
    'settings.notifications.emailDesc': 'Erinnerungs-E-Mails für Ihre Gewohnheiten erhalten',
    'settings.notifications.inApp': 'In-App-Benachrichtigungen',
    'settings.notifications.inAppDesc': 'Benachrichtigungen in der App anzeigen',
    'settings.notifications.save': 'Benachrichtigungseinstellungen Speichern',
    'theme.light': 'Hell',
    'theme.dark': 'Dunkel',
    'theme.system': 'Systemstandard',
    'toast.profileUpdated': 'Profil Aktualisiert',
    'toast.profileUpdatedDesc': 'Ihre Profilinformationen wurden erfolgreich aktualisiert.',
    'toast.passwordChanged': 'Passwort Geändert',
    'toast.passwordChangedDesc': 'Ihr Passwort wurde erfolgreich geändert.',
    'toast.preferencesSaved': 'Präferenzen Gespeichert',
    'toast.preferencesSavedDesc': 'Ihre Präferenzen wurden erfolgreich aktualisiert.',
    'toast.notificationsSaved': 'Benachrichtigungseinstellungen Gespeichert',
    'toast.notificationsSavedDesc': 'Ihre Benachrichtigungspräferenzen wurden aktualisiert.',
  },
  japanese: {
    'nav.dashboard': 'ダッシュボード',
    'nav.habits': '習慣',
    'nav.insights': 'インサイト',
    'nav.settings': '設定',
    'nav.logout': 'ログアウト',
    'nav.login': 'ログイン',
    'nav.getStarted': '始める',
    'settings.title': '設定',
    'settings.subtitle': 'アカウントの設定と環境設定を管理する',
    'settings.tabs.profile': 'プロフィール',
    'settings.tabs.password': 'パスワード',
    'settings.tabs.preferences': '環境設定',
    'settings.tabs.notifications': '通知',
    'settings.profile.title': 'プロフィール情報',
    'settings.profile.description': '個人情報を更新する',
    'settings.profile.name': '氏名',
    'settings.profile.email': 'メールアドレス',
    'settings.profile.save': '変更を保存',
    'settings.password.title': 'パスワード変更',
    'settings.password.description': 'アカウントの安全性を保つためにパスワードを更新する',
    'settings.password.current': '現在のパスワード',
    'settings.password.new': '新しいパスワード',
    'settings.password.confirm': '新しいパスワードの確認',
    'settings.password.requirement': 'パスワードは8文字以上である必要があります',
    'settings.password.change': 'パスワードを変更',
    'settings.preferences.title': '環境設定',
    'settings.preferences.description': 'アプリの体験をカスタマイズする',
    'settings.preferences.theme': 'テーマ',
    'settings.preferences.language': '言語',
    'settings.preferences.timezone': 'タイムゾーン',
    'settings.preferences.save': '環境設定を保存',
    'settings.notifications.title': '通知設定',
    'settings.notifications.description': '通知の方法とタイミングを管理する',
    'settings.notifications.email': 'メール通知',
    'settings.notifications.emailDesc': '習慣のリマインダーメールを受信する',
    'settings.notifications.inApp': 'アプリ内通知',
    'settings.notifications.inAppDesc': 'アプリ内で通知を表示する',
    'settings.notifications.save': '通知設定を保存',
    'theme.light': 'ライト',
    'theme.dark': 'ダーク',
    'theme.system': 'システムデフォルト',
    'toast.profileUpdated': 'プロフィールが更新されました',
    'toast.profileUpdatedDesc': 'プロフィール情報が正常に更新されました。',
    'toast.passwordChanged': 'パスワードが変更されました',
    'toast.passwordChangedDesc': 'パスワードが正常に変更されました。',
    'toast.preferencesSaved': '環境設定が保存されました',
    'toast.preferencesSavedDesc': '環境設定が正常に更新されました。',
    'toast.notificationsSaved': '通知設定が保存されました',
    'toast.notificationsSavedDesc': '通知設定が更新されました。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'english';
  });

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  React.useEffect(() => {
    localStorage.setItem('language', language);
    console.log('Language changed to:', language);
  }, [language]);

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
};
